<a href="https://colab.research.google.com/github/brcmipn/MachineLearningGoogleColab/blob/main/03_TratadoDeVariablesCategoricas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#Clase 3
#Limpiar datos numericos nulos con promedio

#Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot


#Ruta del archivo CSV en Github
url = 'https://raw.githubusercontent.com/brcmipn/MachineLearningGoogleColab/main/0_Data.csv'
datos = pd.read_csv(url)

#Visualizar datos
datos


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [122]:
#Importa variables predictoras y dependientes
X = datos.iloc[:, :-1].values
Y = datos.iloc[:, 2:3].values

In [123]:
#Imprime variables independientes
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [77]:
#Imprime variables dependientes
Y

array([[72000.],
       [48000.],
       [54000.],
       [61000.],
       [   nan],
       [58000.],
       [52000.],
       [79000.],
       [83000.],
       [67000.]])

In [125]:
#Tratado de valores nulos
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean' )
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.fit_transform(X[:, 1:3])

In [126]:
#Imprime variables rellenadas con promedio
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [127]:
#Creación de etiquetas para variables categóricas
from sklearn.preprocessing import LabelEncoder
labelEncoder_x = LabelEncoder()
X[:, 0] = labelEncoder_x.fit_transform(X[:, 0])

In [145]:
#Imprime variables con etiquetas
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [146]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)


In [147]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)